version: "3.4"
services:
  dev-api:
    container_name: cbs-dev-api
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: development
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - 4040:4040
    command: yarn dev
    env_file:
      - ../../.env.development

